language: node_js
os: linux
sudo: required
dist: trusty
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
    - documentation/www/node_modules
node_js:
  - '6'
env:
  - CXX=g++-4.8
addons:
  sources:
    - ubuntu-toolchain-r-test
  apt:
    packages:
      - g++-4.8
      - xvfb
env:
  CXX=g++-4.8

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - npm install
  - npm run build:release -- --bail
  - npm run test:travis
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/pvw-presenter.git
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
